POST http://localhost:8080/
Content-Type: application/json

{
  "headers": {
    "authorization":"##########",
    "request_id":"b490b3c6-479c-4328-96b0-07504d1188a5"
  },
  "request_type":"action",
  "payload": {
    "devices": [
      {
        "id": "torchere",
        "capabilities": [
          {
            "type": "devices.capabilities.on_off",
            "state": {
              "instance": "on",
              "value": false
            }
          }
        ]
      }
    ]
  }
}